language: python
python: 3.5
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - otree test
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/travis_ci_test

    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist
after_success:
  - >
    [ "$TRAVIS_BRANCH" == "master" ]
    && curl -X POST -H "Content-Type: application/json"
    --data '{"docker_tag_name": "latest"}'
    https://registry.hub.docker.com/u/awilab/otree/trigger/$DOCKER_HUB_TOKEN/
notifications:
  email:
    recipients:
      - lab@awi.uni-heidelberg.de
    on_success: change
    on_failure: always
