version: "2"

services:

  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PG_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      db-net:

  otree:
    # uncomment if you want to build an image locally
    # if using Docker Hub, leave this line commented out:
    # build: ./
    image: otree
    environment:
      DATABASE_URL: "postgres://${PG_USER}:${PG_PASSWORD}@database/${PG_DATABASE}"
      OTREE_ADMIN_PASSWORD: ${OTREE_ADMIN_PASSWORD}
      OTREE_PRODUCTION: ${OTREE_PRODUCTION}
      OTREE_AUTH_LEVEL: ${OTREE_AUTH_LEVEL}
    ports:
      - ${OTREE_PORT}:80
    volumes:
      - "otree-resetdb:/opt/init"
    # Uncomment for live editing
    #  - ./:/opt/otree
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-net
      - redis-net

  redis:
    image: redis
    command: "redis-server"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - redis-net

volumes:
  database:
  otree-resetdb:

networks:
  db-net:
  redis-net:
